apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgdk-appk
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: resources/manifests/bgdk-kustomize
    repoURL: https://github.com/RedHatWorkshops/argocd-getting-started
    targetRevision: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sync:
    comparedTo:
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      source:
        path: resources/manifests/bgdk-kustomize
        repoURL: https://github.com/RedHatWorkshops/argocd-getting-started
        targetRevision: openshift-gitops
